# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# Zoltan Szalai <defaultdict@gmail.com>, 2015
msgid ""
msgstr ""
"Project-Id-Version: Django REST framework\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-01-30 16:23+0000\n"
"PO-Revision-Date: 2015-01-30 16:27+0000\n"
"Last-Translator: Thomas Christie <tom@tomchristie.com>\n"
"Language-Team: Hungarian (http://www.transifex.com/projects/p/django-rest-framework/language/hu/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: hu\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: authentication.py:69
msgid "Invalid basic header. No credentials provided."
msgstr "Érvénytelen basic fejlécmező. Nem voltak megadva azonosítók."

#: authentication.py:72
msgid "Invalid basic header. Credentials string should not contain spaces."
msgstr "Érvénytelen basic fejlécmező. Az azonosító karakterlánc nem tartalmazhat szóközöket."

#: authentication.py:78
msgid "Invalid basic header. Credentials not correctly base64 encoded."
msgstr "Érvénytelen basic fejlécmező. Az azonosítók base64 kódolása nem megfelelő."

#: authentication.py:90
msgid "Invalid username/password."
msgstr "Érvénytelen felhasználónév/jelszó."

#: authentication.py:156
msgid "Invalid token header. No credentials provided."
msgstr "Érvénytelen token fejlécmező. Nem voltak megadva azonosítók."

#: authentication.py:159
msgid "Invalid token header. Token string should not contain spaces."
msgstr "Érvénytelen token fejlécmező. A token karakterlánc nem tartalmazhat szóközöket."

#: authentication.py:168
msgid "Invalid token."
msgstr "Érvénytelen token."

#: authentication.py:171
msgid "User inactive or deleted."
msgstr "A felhasználó nincs aktiválva vagy törölve lett."

#: exceptions.py:38
msgid "A server error occurred."
msgstr "Szerver oldali hiba történt."

#: exceptions.py:73
msgid "Malformed request."
msgstr "Hibás kérés."

#: exceptions.py:78
msgid "Incorrect authentication credentials."
msgstr "Hibás azonosítók."

#: exceptions.py:83
msgid "Authentication credentials were not provided."
msgstr "Nem voltak megadva azonosítók."

#: exceptions.py:88
msgid "You do not have permission to perform this action."
msgstr "Nincs jogosultsága a művelet végrehajtásához."

#: exceptions.py:93
msgid "Not found."
msgstr "Nem található."

#: exceptions.py:98
msgid "Method \"{method}\" not allowed."
msgstr "A \"{method}\" metódus nem megengedett."

#: exceptions.py:109
msgid "Could not satisfy the request Accept header."
msgstr "A kérés Accept fejlécmezőjét nem lehetett kiszolgálni."

#: exceptions.py:121
msgid "Unsupported media type \"{media_type}\" in request."
msgstr "Nem támogatott média típus \"{media_type}\" a kérésben."

#: exceptions.py:134
msgid "Request was throttled."
msgstr "A kérés korlátozva lett."

#: fields.py:153 relations.py:132 relations.py:156 validators.py:77
#: validators.py:155
msgid "This field is required."
msgstr "Ennek a mezőnek a megadása kötelező."

#: fields.py:154
msgid "This field may not be null."
msgstr "Ez a mező nem lehet null értékű."

#: fields.py:487 fields.py:515
msgid "\"{input}\" is not a valid boolean."
msgstr "Az \"{input}\" nem egy érvényes logikai érték."

#: fields.py:550
msgid "This field may not be blank."
msgstr "Ez a mező nem lehet üres."

#: fields.py:551 fields.py:1324
msgid "Ensure this field has no more than {max_length} characters."
msgstr "Bizonyosodjon meg arról, hogy ez a mező legfeljebb {max_length} karakterből áll."

#: fields.py:552
msgid "Ensure this field has at least {min_length} characters."
msgstr "Bizonyosodjon meg arról, hogy ez a mező legalább {min_length} karakterből áll."

#: fields.py:587
msgid "Enter a valid email address."
msgstr "Adjon meg egy érvényes e-mail címet!"

#: fields.py:604
msgid "This value does not match the required pattern."
msgstr "Ez az érték nem illeszkedik a szükséges mintázatra."

#: fields.py:615
msgid ""
"Enter a valid \"slug\" consisting of letters, numbers, underscores or "
"hyphens."
msgstr "Az URL barát cím csak betűket, számokat, aláhúzásokat és kötőjeleket tartalmazhat."

#: fields.py:627
msgid "Enter a valid URL."
msgstr "Adjon meg egy érvényes URL-t!"

#: fields.py:638
msgid "\"{value}\" is not a valid UUID."
msgstr ""

#: fields.py:657
msgid "A valid integer is required."
msgstr "Egy érvényes egész szám megadása szükséges."

#: fields.py:658 fields.py:692 fields.py:725
msgid "Ensure this value is less than or equal to {max_value}."
msgstr "Bizonyosodjon meg arról, hogy ez az érték legfeljebb {max_value}."

#: fields.py:659 fields.py:693 fields.py:726
msgid "Ensure this value is greater than or equal to {min_value}."
msgstr "Bizonyosodjon meg arról, hogy ez az érték legalább {min_value}."

#: fields.py:660 fields.py:694 fields.py:730
msgid "String value too large."
msgstr "A karakterlánc túl hosszú."

#: fields.py:691 fields.py:724
msgid "A valid number is required."
msgstr "Egy érvényes szám megadása szükséges."

#: fields.py:727
msgid "Ensure that there are no more than {max_digits} digits in total."
msgstr "Bizonyosodjon meg arról, hogy a számjegyek száma összesen legfeljebb {max_digits}."

#: fields.py:728
msgid ""
"Ensure that there are no more than {max_decimal_places} decimal places."
msgstr "Bizonyosodjon meg arról, hogy a tizedes tört törtrészében levő számjegyek száma összesen legfeljebb {max_decimal_places}."

#: fields.py:729
msgid ""
"Ensure that there are no more than {max_whole_digits} digits before the "
"decimal point."
msgstr "Bizonyosodjon meg arról, hogy a tizedes tört egész részében levő számjegyek száma összesen legfeljebb {max_whole_digits}."

#: fields.py:813
msgid "Datetime has wrong format. Use one of these formats instead: {format}."
msgstr "A dátum formátuma hibás. Használja ezek valamelyikét helyette: {format}."

#: fields.py:814
msgid "Expected a datetime but got a date."
msgstr "Időt is tartalmazó dátum helyett egy időt nem tartalmazó dátum lett elküldve."

#: fields.py:878
msgid "Date has wrong format. Use one of these formats instead: {format}."
msgstr "A dátum formátuma hibás. Használja ezek valamelyikét helyette: {format}."

#: fields.py:879
msgid "Expected a date but got a datetime."
msgstr "Időt nem tartalmazó dátum helyett egy időt is tartalmazó dátum lett elküldve."

#: fields.py:936
msgid "Time has wrong format. Use one of these formats instead: {format}."
msgstr "Az idő formátuma hibás. Használja ezek valamelyikét helyette: {format}."

#: fields.py:992 fields.py:1036
msgid "\"{input}\" is not a valid choice."
msgstr "Az \"{input}\" nem egy érvényes elem."

#: fields.py:1037 fields.py:1151 serializers.py:482
msgid "Expected a list of items but got type \"{input_type}\"."
msgstr "Elemek listája helyett \"{input_type}\" lett elküldve."

#: fields.py:1067
msgid "No file was submitted."
msgstr "Semmilyen fájl sem került feltöltésre."

#: fields.py:1068
msgid ""
"The submitted data was not a file. Check the encoding type on the form."
msgstr "Az elküldött adat nem egy fájl volt. Ellenőrizze a kódolás típusát az űrlapon!"

#: fields.py:1069
msgid "No filename could be determined."
msgstr "A fájlnév nem megállapítható."

#: fields.py:1070
msgid "The submitted file is empty."
msgstr "A küldött fájl üres."

#: fields.py:1071
msgid ""
"Ensure this filename has at most {max_length} characters (it has {length})."
msgstr "Bizonyosodjon meg arról, hogy a fájlnév legfeljebb {max_length} karakterből áll (jelenlegi hossza: {length})."

#: fields.py:1113
msgid ""
"Upload a valid image. The file you uploaded was either not an image or a "
"corrupted image."
msgstr "Töltsön fel egy érvényes képfájlt! A feltöltött fájl nem kép volt, vagy megsérült."

#: fields.py:1188
msgid "Expected a dictionary of items but got type \"{input_type}\"."
msgstr ""

#: pagination.py:221
msgid "Invalid page \"{page_number}\": {message}."
msgstr "Érvénytelen oldal \"{page_number}\": {message}."

#: pagination.py:442
msgid "Invalid cursor"
msgstr ""

#: relations.py:133
msgid "Invalid pk \"{pk_value}\" - object does not exist."
msgstr "Érvénytelen pk \"{pk_value}\" - az objektum nem létezik."

#: relations.py:134
msgid "Incorrect type. Expected pk value, received {data_type}."
msgstr "Helytelen típus. pk érték helyett {data_type} lett elküldve."

#: relations.py:157
msgid "Invalid hyperlink - No URL match."
msgstr "Érvénytelen link - Nem illeszkedő URL."

#: relations.py:158
msgid "Invalid hyperlink - Incorrect URL match."
msgstr "Érvénytelen link. - Eltérő URL illeszkedés."

#: relations.py:159
msgid "Invalid hyperlink - Object does not exist."
msgstr "Érvénytelen link - Az objektum nem létezik."

#: relations.py:160
msgid "Incorrect type. Expected URL string, received {data_type}."
msgstr "Helytelen típus. URL karakterlánc helyett {data_type} lett elküldve."

#: relations.py:295
msgid "Object with {slug_name}={value} does not exist."
msgstr "Nem létezik olyan objektum, amelynél {slug_name}={value}."

#: relations.py:296
msgid "Invalid value."
msgstr "Érvénytelen érték."

#: serializers.py:299
msgid "Invalid data. Expected a dictionary, but got {datatype}."
msgstr "Érvénytelen adat. Egy dictionary helyett {datatype} lett elküldve."

#: validators.py:22
msgid "This field must be unique."
msgstr "Ennek a mezőnek egyedinek kell lennie."

#: validators.py:76
msgid "The fields {field_names} must make a unique set."
msgstr "A {field_names} mezőnevek nem tartalmazhatnak duplikátumot."

#: validators.py:219
msgid "This field must be unique for the \"{date_field}\" date."
msgstr "A mezőnek egyedinek kell lennie a \"{date_field}\" dátumra."

#: validators.py:234
msgid "This field must be unique for the \"{date_field}\" month."
msgstr "A mezőnek egyedinek kell lennie a \"{date_field}\" hónapra."

#: validators.py:247
msgid "This field must be unique for the \"{date_field}\" year."
msgstr "A mezőnek egyedinek kell lennie a \"{date_field}\" évre."

#: versioning.py:39
msgid "Invalid version in \"Accept\" header."
msgstr "Érvénytelen verzió az \"Accept\" fejlécmezőben."

#: versioning.py:70 versioning.py:112
msgid "Invalid version in URL path."
msgstr "Érvénytelen verzió az URL elérési útban."

#: versioning.py:138
msgid "Invalid version in hostname."
msgstr "Érvénytelen verzió a hosztnévben."

#: versioning.py:160
msgid "Invalid version in query parameter."
msgstr "Érvénytelen verzió a lekérdezési paraméterben."

#: authtoken/serializers.py:20
msgid "User account is disabled."
msgstr "A felhasználó tiltva van."

#: authtoken/serializers.py:23
msgid "Unable to log in with provided credentials."
msgstr "A megadott azonosítókkal nem lehet bejelentkezni."

#: authtoken/serializers.py:26
msgid "Must include \"username\" and \"password\"."
msgstr "Tartalmaznia kell a \"felhasználónevet\" és a \"jelszót\"."
